version: "3.9"

services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  url-service:
    build: ./services/url-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/shorturl
    restart: unless-stopped
    depends_on:
      - mongo

  analytics-service:
    build: ./services/analytics-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/analytics
    restart: unless-stopped
    depends_on:
      - mongo

  qr-service:
    build: ./services/qr-service
    environment:
      - BASE_URL=https://shorturl.jettyjaaaa.space
    restart: unless-stopped
    depends_on:
      - url-service

  nginx:
    build: ./nginx
    container_name: nginx-shorturl
    ports:
      - "80:80"
    depends_on:
      - url-service
      - analytics-service
      - qr-service

volumes:
  mongo-data:
